AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys an EKS cluster in a new VPC (qs-1p7nknoht)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC network configuration
        Parameters:
          - AvailabilityZones
          - VPCCIDR
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - PrivateSubnet3ID
          - PublicSubnet1AID
          - PublicSubnet2AID
          - PublicSubnet3AID
          - RemoteAccessCIDR
      - Label:
          default: Amazon EC2 configuration
        Parameters:
          - KeyPairName
      - Label:
          default: Amazon EKS configuration
        Parameters:
          - NodeInstanceType
          - NumberOfNodes
          - MinNumberOfNodes
          - MaxNumberOfNodes
          - NodeGroupName
          - NodeVolumeSize
          - AdditionalEKSAdminArns
          - KubernetesVersion
      - Label:
          default: BusyCloud source configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - LambdaZipsBucketName
      - Label:
          default: Application cluster configuration
        Parameters:
          - Cluster
          - Environment
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      KeyPairName:
        Description: The name of an existing public/private key pair, which allows you to securely connect to your instance after it launches
      PrivateSubnet1AID:
        Description: Private 'a' Subnet ID for the Resources
      PrivateSubnet2AID:
        Description: Private 'b' Subnet ID for the Resources      
      PrivateSubnet3AID:
        Description: Private 'c' Subnet ID for the Resources
      PublicSubnet1ID:
        Description: public 'a' Subnet ID for the Resources
      PublicSubnet2ID:
        Description: public 'b' Subnet ID for the Resources
      PublicSubnet3ID:
        Description: public 'c' Subnet ID for the Resources
      QSS3BucketName:
        Description: BusyCloud S3 bucket name
      QSS3KeyPrefix:
        Description: BusyCloud S3 key prefix
      Cluster:
        Description: BusyCloud target EKS cluster
      Environment:
        Description: BusyCloud application target runtime environment
      RemoteAccessCIDR:
        Description: Allowed external access CIDR
      VPCID:
        Description: The VPC ID for the Resources created in Stack
      NodeInstanceType:
        Description: Nodes instance type
      NumberOfNodes:
        Description: Number of worker nodes
      MinNumberOfNodes:
        Description: Minimum number of worker nodes for the auto-scaling group
      MaxNumberOfNodes:
        Description: Maximum number of worker nodes for the auto-scaling group
      NodeGroupName:
        Description: Node group name
      NodeVolumeSize:
        Description: Node volume size
      AdditionalEKSAdminArns:
        Description: Additional EKS admin ARNs
      KubernetesVersion:
        Description: Kubernetes version
      LambdaZipsBucketName:
        Description: Lambda zips bucket name
Parameters:
  Cluster:
    Type: String
    Default: "development"
  Environment:
    Type: String
    Default: "dev"
  AvailabilityZones:
    Description: The list of Availability Zones to use for the subnets in the VPC. Three
      Availability Zones are used for this deployment, and the logical order of your
      selections is preserved.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you
      to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  PrivateSubnet1AID:
    Description: Private 'a' Subnet ID for the Resources
    Type: 'AWS::EC2::Subnet::Id'
  PrivateSubnet2AID:
    Description: Private 'b' Subnet ID for the Resources
    Type: 'AWS::EC2::Subnet::Id'
  PrivateSubnet3AID:
    Description: Private 'c' Subnet ID for the Resources
    Type: 'AWS::EC2::Subnet::Id'
  PublicSubnet1ID:
    Description: public 'a' Subnet ID for the Resources
    Type: 'AWS::EC2::Subnet::Id'
  PublicSubnet2ID:
    Description: public 'b' Subnet ID for the Resources
    Type: 'AWS::EC2::Subnet::Id'
  PublicSubnet3ID:
    Description: public 'c' Subnet ID for the Resources
    Type: 'AWS::EC2::Subnet::Id'
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: BusyCloud bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Description: S3 bucket name for the BusyCloud assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: BusyCloud key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: assets/
    Description: S3 key prefix for the BusyCloud assets. BusyCloud key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the instances We recommend
      that you set this value to a trusted IP range.
    Type: String
  VPCID:
    Description: The VPC ID for the Resources created in Stack
    Type: 'AWS::EC2::VPC::Id'
  AdditionalEKSAdminArns:
    Default: ""
    Description: "[OPTIONAL] Comma separated list of IAM user/role Amazon Resource Names (ARNs) to be granted admin access to the EKS cluster"
    Type: CommaDelimitedList
  NodeInstanceType:
    Default: t3.medium
    AllowedValues:
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.24xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.18xlarge
      - i3.large
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - i3.16xlarge
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge
      - x1.16xlarge
      - x1.32xlarge
      - p2.xlarge
      - p2.8xlarge
      - p2.16xlarge
      - p3.2xlarge
      - p3.8xlarge
      - p3.16xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.12xlarge
      - r5.24xlarge
      - r5d.large
      - r5d.xlarge
      - r5d.2xlarge
      - r5d.4xlarge
      - r5d.12xlarge
      - r5d.24xlarge
      - z1d.large
      - z1d.xlarge
      - z1d.2xlarge
      - z1d.3xlarge
      - z1d.6xlarge
      - z1d.12xlarge
    ConstraintDescription: Must be a valid EC2 instance type
    Description: The type of EC2 instance for the node instances.
    Type: String
  NumberOfNodes:
    Default: 3
    Description: The number of Amazon EKS worker node instances. The default is one for each of the three Availability Zones.
    Type: Number
  MinNumberOfNodes:
    Default: 3
    Description: The minimum number of Amazon EKS worker node instances. The default is one for each of the three Availability Zones.
    Type: Number
  MaxNumberOfNodes:
    Default: 3
    Description: The maximun number of Amazon EKS worker node instances. The default is one for each of the three Availability Zones.
    Type: Number
  NodeGroupName:
    Default: Default
    Description: The name for EKS node group.
    Type: String
  NodeVolumeSize:
    Default: 20
    Description: "The size for the node's root EBS volumes."
    Type: String
  KubernetesVersion:
    Type: String
    AllowedValues: [ "1.12", "1.11", "1.10" ]
    Description: The Kubernetes control plane version.
    Default: "1.12"
  LambdaZipsBucketName:
    Description: '[OPTIONAL] The name of the S3 bucket where the Lambda .zip files should be placed. If you leave this parameter blank, an S3 bucket will be created.'
    Type: String
    Default: ''
Conditions:
  MaxNodes: !Not [ !Equals [ !Ref MaxNumberOfNodes, "" ] ]
  MinNodes: !Not [ !Equals [ !Ref MinNumberOfNodes, "" ] ]
Rules:
  EKSSupport:
    Assertions:
      - AssertDescription: Your AWS Region does *NOT* yet support Amazon EKS
        Assert: !Contains
          -  - us-west-2
             - us-east-1
             - us-east-2
             - eu-west-1
             - eu-west-2
             - eu-west-3
             - eu-north-1
             - eu-central-1
             - ap-southeast-1
             - ap-southeast-2
             - ap-northeast-1
             - ap-northeast-2
             - ap-south-1
          - !Ref 'AWS::Region'
Resources:
  # VPCStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/amazon-vpc.template.yaml'
  #     Parameters:
  #       AvailabilityZones: !Join [ ',', !Ref 'AvailabilityZones' ]
  #       KeyPairName: !Ref 'KeyPairName'
  #       NumberOfAZs: '3'
  #       PrivateSubnet1ACIDR: !Ref 'PrivateSubnet1CIDR'
  #       PrivateSubnet2ACIDR: !Ref 'PrivateSubnet2CIDR'
  #       PrivateSubnet3ACIDR: !Ref 'PrivateSubnet3CIDR'
  #       PrivateSubnetATag2: "kubernetes.io/role/internal-elb="
  #       PublicSubnet1CIDR: !Ref 'PublicSubnet1CIDR'
  #       PublicSubnet2CIDR: !Ref 'PublicSubnet2CIDR'
  #       PublicSubnet3CIDR: !Ref 'PublicSubnet3CIDR'
  #       PublicSubnetTag2: "kubernetes.io/role/elb="
  #       VPCCIDR: !Ref 'VPCCIDR'
  EKSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/amazon-eks.template.yaml'
      Parameters:
        Cluster: !Ref Cluster
        Environment: !Ref 'Environment'
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        PublicSubnet3ID: !Ref PublicSubnet3ID
        KeyPairName: !Ref KeyPairName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        PrivateSubnet1ID: !Ref PrivateSubnet1AID
        PrivateSubnet2ID: !Ref PrivateSubnet2AID
        PrivateSubnet3ID: !Ref PrivateSubnet3AID
        NumberOfNodes: !Ref NumberOfNodes
        MinNumberOfNodes: !If [ MinNodes, !Ref MinNumberOfNodes, !Ref NumberOfNodes ]
        MaxNumberOfNodes: !If [ MaxNodes, !Ref MaxNumberOfNodes, !Ref NumberOfNodes ]
        NodeGroupName: !Ref NodeGroupName
        NodeVolumeSize: !Ref NodeVolumeSize
        LambdaZipsBucketName: !Ref LambdaZipsBucketName
        NodeInstanceType: !Ref NodeInstanceType
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        AdditionalEKSAdminArns: !Join [ ",", !Ref AdditionalEKSAdminArns ]
        VPCID: !Ref VPCID
        KubernetesVersion: !Ref KubernetesVersion
        ProvisionClusterAutoScaler: Enabled
        BastionInstanceType: t2.small
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/amazon-aurora.template.yaml'
      Parameters:
        AvailabilityZones: !Join [ ',', !Ref 'AvailabilityZones' ]
        PrivateSubnet1ID: !Ref PrivateSubnet1AID
        PrivateSubnet2ID: !Ref PrivateSubnet2AID
        PrivateSubnet3ID: !Ref PrivateSubnet3AID
        EKSNodeSecurityGroup: !GetAtt EKSStack.Outputs.EKSNodeSecurityGroup
        BastionSecurityGroup: !GetAtt EKSStack.Outputs.BastionSecurityGroup
        VPCID: !Ref VPCID
        Cluster: !Ref Cluster
        Environment: !Ref Environment
  PricerCentralStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/pricer-central.template.yaml'
      Parameters:
        KubeConfigPath: !GetAtt EKSStack.Outputs.KubeConfigPath
        KubeConfigKmsContext: !GetAtt EKSStack.Outputs.KubeConfigKmsContext
        KubeManifestLambdaArn: !GetAtt EKSStack.Outputs.KubeManifestLambdaArn
        HelmLambdaArn: !GetAtt EKSStack.Outputs.HelmLambdaArn
        Cluster: !Ref 'Cluster'
        Environment: !Ref 'Environment'
        DbUsername: !Join ['', ['{{resolve:secretsmanager:', !GetAtt DatabaseStack.Outputs.DBRDSSecret, ':SecretString:username}}' ]]
        DbPassword: !Join ['', ['{{resolve:secretsmanager:', !GetAtt DatabaseStack.Outputs.DBRDSSecret, ':SecretString:password}}' ]]
Outputs:
  KubeConfigPath:
    Value: !GetAtt EKSStack.Outputs.KubeConfigPath
  HelmLambdaArn:
    Value: !GetAtt EKSStack.Outputs.HelmLambdaArn
  KubeManifestLambdaArn:
    Value: !GetAtt EKSStack.Outputs.KubeManifestLambdaArn
  BastionIP:
    Value: !GetAtt EKSStack.Outputs.BastionIP
  EKSClusterName:
    Value: !GetAtt EKSStack.Outputs.EKSClusterName
